[package]
name = "proto-to-rust"
description = "A small binary to convert protobuf specs to Rust."

version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
prost-build.workspace = true
