// supress lint warnings for bindgen-generated bindings
#![allow(clippy::all)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(missing_debug_implementations)]
#![allow(non_snake_case)]
#![allow(unnecessary_transmutes)]

use std::ffi::c_void;

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// constants not generated by bindgen, see https://github.com/rust-lang/rust-bindgen/issues/316
pub const CU_LAUNCH_PARAM_END: *mut c_void = 0 as *mut c_void;
pub const CU_LAUNCH_PARAM_BUFFER_POINTER: *mut c_void = 1 as *mut c_void;
pub const CU_LAUNCH_PARAM_BUFFER_SIZE: *mut c_void = 2 as *mut c_void;
