name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCS_RS: 1 # make sure cuda-sys uses vendored headers
    steps:
    - uses: actions/checkout@v3
    - name: Cargo check (default features)
      run: cargo check
    - name: Cargo check check (all features)
      run: cargo check --all-features
    - name: Cargo doc
      run: cargo doc --no-deps --all-features
    - name: Test kn-graph
      run: cargo test -p kn-graph
